### ISSUE TITLE
Create main banner component

### ISSUE THREAD

**Issue by victorstein** [victorstein/TGC#16]
Develop a main banner component for the app to enhance visual appeal and convey important messages effectively. The main banner serves as a prominent section at the top of the app, capturing user attention and delivering key information or visuals related to the app purpose.

Requirements:
- [ ] It must be responsive, ensuring optimal display across various devices and screen sizes.
- [ ] The component should have the props: title, description, bgImage, redirectId, and optional duration. 
- [ ] Create the dark variant of this component

![Image](https://github.com/victorstein/TGC/assets/11080740/8c60067f-0cc2-44a1-a2bb-7bc82b184100)

**Comment by carloslenondavis** [comment]
Hi @victorstein,

-  Wich is the idea of the redirectId field in this main banner.
- Which type of value this redirectId will receive?
- Which is the type of duration prop?

**Comment by victorstein** [comment]
* Wich is the idea of the redirectId field in this main banner.
	`The banner must have an action when pressed; therefore, a routeId will be used as the redirect param. To put this on perspective. This component will redirect to a view where the promoted article is visible, then using the id the article view will fetch the data it needs to display it.`

 * Which type of value this redirectId will receive?
 `Should be a string`

* Which is the type of duration prop?
`Should be a number`

**Comment by andadevs** [comment]
That dark color on top of the background is playing like ind of filter with black color and opacity. ?

**Comment by andadevs** [comment]
> That dark color on top of the background playing is a kind of filter with black color and opacity or is part of the image? If not how I cand add that kind of filter iwth opacity with tailwind?
> 
> ![image](https://private-user-images.githubusercontent.com/4239218/308444091-61e67097-b1d1-4270-b9fa-5790c7701651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDIxNTQsIm5iZiI6MTcwOTEwMTg1NCwicGF0aCI6Ii80MjM5MjE4LzMwODQ0NDA5MS02MWU2NzA5Ny1iMWQxLTQyNzAtYjlmYS01NzkwYzc3MDE2NTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDYzMDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI5YTgxYzg4Yjg4OGYzNWIzOTMxM2ZmNmUyNTI4MDA2YThiOTE2MzQ1N2I3ZTdhNjYwYjk4YzhmMjFiNjdkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UaZ8l6mZF98PWDp9qERGtIHq6-zRaQBy-Zue1V6yHbw)

Never mind, I already check

**Comment by carloslenondavis** [comment]
@victorstein is this the right way to share the article Id from the banner to the view?

![image](https://github.com/victorstein/TGC/assets/4239218/5dbdee2d-b3ce-4fa8-8d34-fe6629763512)
