### ISSUE TITLE
Status bar color in production app

### ISSUE THREAD

**Issue by victorstein** [victorstein/TGC#24]
Change status bar color when in dark mode

![Image](https://github.com/victorstein/TGC/assets/11080740/7e9ab8d7-93f3-49d8-bbb3-9df0c8d7e920)

**Comment by carloslenondavis** [comment]
@victorstein which should be the right name for the branch related to this issue?
`bugfix/...` or `feature/BUMP/...` or `feature/...` or which one else? because the change is not a new feature neither a bug, it just add a pending style

**Comment by victorstein** [comment]
This one would be under the `fix/` namespace since it is indeed a bug. This behavior should have been covered by the dark theme PR

**Comment by carloslenondavis** [comment]
The change is related to align the status bar style with the figma design right?

**Comment by victorstein** [comment]
Actually is about making the status bar change color based on the theme dark or light
