### ISSUE TITLE
Create Playstore assets and general description

### ISSUE THREAD

**Issue by victorstein** [victorstein/TGC#36]
Requirements:

## Contents requirements
`Feel free to use Chat-gpt for any of these`
- [x] All content must be created in `Español (Latinoamérica) – es-419`.
- [x] A brief description must be created (80 characters max)
- [x] A full description must be created (4000 characters max)

## Media requirements
- [x] Application Icon must be a PNG or jpeg (max 1 MB) in 512 x 512 dimensions.
       Follow Playstore [best practices for app icons](https://developer.android.com/distribute/google-play/resources/icon-design-specifications)
- [x] Application must have functionalities media 1024x500
- [ ] *optional* a short video uploaded to YouTube to demonstrate the functionality of the app
- [x] Application must have between 2 and 8 captured media screenshots. The screenshots must be PNG or jpeg (8 MB max) with an aspect ratio of 16:9 or 9:16. [This](https://studio.app-mockup.com/) app looks interesting to generate the screenshots
- [x] Application must have between 2 and 8 captured media screenshots for 7-inch tablets. The screenshots must be PNG or jpeg (8 MB max) with an aspect ratio of 16:9 or 9:16.
- [x] Application must have between 2 and 8 captured media screenshots for 10-inch tablets. The screenshots must be PNG or jpeg (8 MB max) with an aspect ratio of 16:9 or 9:16.

**Comment by eMustang92** [comment]
:speech_balloon:
### Contents requirements

**Breve descripción (80 caracteres máximo):**
"Descubre lo último en tecnología, juegos y código en TGC: ¡tu fuente de podcasts y blogs favorita!

**Descripción completa (4000 caracteres como máximo):**

¡Bienvenido a TGC (Tecnología, Juegos y Código)! Sumérgete en el fascinante mundo de la tecnología, los videojuegos y la programación con nuestra aplicación de podcasts y blogs. Estamos aquí para mantenerte actualizado con las últimas noticias, reseñas, análisis y tendencias en estos emocionantes campos.

En TGC, encontrarás una amplia gama de contenido cuidadosamente seleccionado para satisfacer tus intereses y curiosidades. Desde reseñas detalladas de los últimos lanzamientos de dispositivos y juegos, hasta tutoriales prácticos sobre programación y desarrollo de software, nuestro equipo de expertos está comprometido en ofrecer información valiosa y entretenida.

¿Eres un apasionado de la tecnología? Explora nuestros podcasts y blogs dedicados a las últimas innovaciones en inteligencia artificial, realidad virtual, dispositivos móviles, gadgets, y más. Te mantendremos al tanto de las noticias más relevantes y de los avances más emocionantes en el mundo tecnológico.

¿Te encanta jugar? Sumérgete en nuestros análisis en profundidad de los últimos videojuegos, descubre consejos y trucos para mejorar tu experiencia de juego, y mantente informado sobre las últimas tendencias en la industria del entretenimiento digital. Ya seas un jugador casual o un entusiasta hardcore, ¡encontrarás algo para ti en TGC!

¿Interesado en el mundo de la programación y el desarrollo de software? Explora nuestros blogs y podcasts que cubren una amplia variedad de lenguajes de programación, herramientas de desarrollo, prácticas de codificación y tendencias emergentes en el campo de la informática. Ya sea que estés aprendiendo a codificar por primera vez o buscando avanzar en tu carrera como desarrollador, ¡tenemos recursos que te ayudarán a alcanzar tus objetivos!

Características destacadas de la aplicación TGC:
- Accede fácilmente a una amplia biblioteca de podcasts y blogs sobre tecnología, juegos y programación.
- Descubre contenido nuevo y relevante recomendado por nuestro equipo de expertos.
- Personaliza tu experiencia de usuario marcando tus podcasts y blogs favoritos.
- Descarga episodios de podcast para escuchar sin conexión, perfecto para viajes o momentos sin conexión a internet.
- Disfruta de una interfaz intuitiva y fácil de usar diseñada para una navegación sin problemas.

Con TGC, siempre estarás un paso adelante en el mundo de la tecnología, los juegos y el código. Descarga nuestra aplicación ahora y únete a nuestra comunidad de entusiastas apasionados por la innovación y el conocimiento. ¡No te pierdas ni un solo episodio!

**Comment by eMustang92** [comment]
:bento:

Application Icon must be a PNG or jpeg (max 1 MB) in 512 x 512 dimensions.
Follow Playstore

![Image](https://github.com/victorstein/TGC/assets/88738020/cf6ca998-023f-4b25-b866-6d4546feced8)

**Comment by eMustang92** [comment]
:bento:

[Apple iPhone 11 Pro Max (1242x2688).zip](https://github.com/victorstein/TGC/files/14503729/Apple.iPhone.11.Pro.Max.1242x2688.zip)

**Comment by eMustang92** [comment]
:bento:


[HTC Nexus 9 (1536x2048).zip](https://github.com/victorstein/TGC/files/14503769/HTC.Nexus.9.1536x2048.zip)

**Comment by eMustang92** [comment]
:bento:


[Apple iPad Pro 13 Inch (2048x2732).zip](https://github.com/victorstein/TGC/files/14503806/Apple.iPad.Pro.13.Inch.2048x2732.zip)

**Comment by victorstein** [comment]
@Mustang9260 el icono del app no es 512 x 512


![Image](https://github.com/victorstein/TGC/assets/11080740/07d42e8d-255a-4f1e-a608-f9271212c0e0)

Tambien asegurate de seguir estos lineamientos:
https://developer.android.com/distribute/google-play/resources/icon-design-specifications

**Comment by victorstein** [comment]
Also you are missing the 1024 x 500 graphic
https://support.google.com/googleplay/android-developer/answer/9866151?hl=en#zippy=%2Cfeature-graphic

**Comment by eMustang92** [comment]
:bento:

Re-load of Logo using the icon design specifications 



![Image](https://github.com/victorstein/TGC/assets/88738020/f2c95a3b-39ad-4fd0-8a0e-6ffea01da714)

**Comment by eMustang92** [comment]
:bento:

Application must have functionalities media 1024x500


![Image](https://github.com/victorstein/TGC/assets/88738020/a72c7e35-6b36-4029-9f1a-c0b163488618)

**Comment by eMustang92** [comment]
:bento:

Re-Upload views of the app for Android

S20 Ultra

[Samsung Galaxy S20 Ultra (1600x3200).zip](https://github.com/victorstein/TGC/files/14552841/Samsung.Galaxy.S20.Ultra.1600x3200.zip)

Tablet HTC Nexus 9

[HTC Nexus 9 (1536x2048).zip](https://github.com/victorstein/TGC/files/14552844/HTC.Nexus.9.1536x2048.zip)
