### ISSUE TITLE
Create splash screen

### ISSUE THREAD

**Issue by victorstein** [victorstein/TGC#4]
Task is to design and implement a splash screen for the application. The splash screen should effectively represent the brand and provide a visually appealing entry point for users as the application loads. 

- [x] Design a visually appealing splash screen consistent with the application's branding guidelines.
- [x] Ensure the splash screen displays for an appropriate duration while the application loads.
- [x] Implement any necessary animations or transitions to enhance user experience.
- [x] Add support for dark mode
- [x] Create splash assets
  - [x]  adaptive-icon
  - [x] favicon
  - [x] icon
  - [x] splash

**Comment by victorstein** [comment]
Current state
![Image](https://github.com/victorstein/TGC/assets/11080740/6a2fdec3-e179-45ac-81b5-90dda76be521)

**Comment by eMustang92** [comment]
Finish task splash assets
