### ISSUE TITLE
Notification component

### ISSUE THREAD

**Issue by victorstein** [victorstein/TGC#8]
The notification component needs to render the following component:
![Image](https://github.com/victorstein/TGC/assets/11080740/011957cf-c254-454f-8a2a-56225e7d88e2)

Requirements:
- [ ] The component should take 4 parameters (photo URL, title, date, redirect)
- [ ] The component should have read and unread state
- [ ] The component should be able to redirect to another screen using the redirect param
- [ ] The component should be able to persist data based on whether the notification has been seen or not

**Comment by victorstein** [comment]
Current questions:
What happens when they touch the notification bell @GustavoGomez092 ?

**Comment by GustavoGomez092** [comment]
(Figma updated) This is a notifications screen where we can store notifications sent via OneSignal every time there is a published post on WordPress

**Comment by GustavoGomez092** [comment]
This section can also be generated via a WordPress Endpoint and we can leave the Push functionality for a later version.

**Comment by carloslenondavis** [comment]
Hi guys

What is de meaning of the border color for each card in the notification list?

Its mean status value which a color is assigned to?

![image](https://github.com/victorstein/TGC/assets/4239218/e876d125-1d2f-4a2a-bbdf-9132c03f3253)

**Comment by victorstein** [comment]
> Hi guys
> 
> What is de meaning of the border color for each card in the notification list?
> 
> Its mean status value which a color is assigned to?
> 
> ![image](https://private-user-images.githubusercontent.com/4239218/306518143-e876d125-1d2f-4a2a-bbdf-9132c03f3253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTcyNTUsIm5iZiI6MTcwODQ5Njk1NSwicGF0aCI6Ii80MjM5MjE4LzMwNjUxODE0My1lODc2ZDEyNS0xZDJmLTRhMmEtYmJkZi05MTMyYzAzZjMyNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDYyOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYwYzkzMTQ2MjhkYzM0ODMwNzZiNTA0NDg3MDdjY2MwNjRhODIxMjM0ODY2YTM0ZDU1NmEyNDkzMzE5M2Y2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gtNtEnGTVG2v8mVSBAD72xLd606evsFxh448citERNg)

That is used to determine read and unread notifications

**Comment by carloslenondavis** [comment]
> > Hi guys
> > What is de meaning of the border color for each card in the notification list?
> > Its mean status value which a color is assigned to?
> > ![image](https://private-user-images.githubusercontent.com/4239218/306518143-e876d125-1d2f-4a2a-bbdf-9132c03f3253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTcyNTUsIm5iZiI6MTcwODQ5Njk1NSwicGF0aCI6Ii80MjM5MjE4LzMwNjUxODE0My1lODc2ZDEyNS0xZDJmLTRhMmEtYmJkZi05MTMyYzAzZjMyNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDYyOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYwYzkzMTQ2MjhkYzM0ODMwNzZiNTA0NDg3MDdjY2MwNjRhODIxMjM0ODY2YTM0ZDU1NmEyNDkzMzE5M2Y2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gtNtEnGTVG2v8mVSBAD72xLd606evsFxh448citERNg)
> 
> That is used to determine read and unread notifications

Thanks for the answer

**Comment by carloslenondavis** [comment]
Hi guys,

Which is the term of Notification, its mean the unit card or means the Notification View with the list of card
So, this feature is related to the card view component of the View with all the list of cards including the "Notificaciones" Title?

I'll appreciate your clarification.

@victorstein

**Comment by victorstein** [comment]
> Hi guys,
> 
> Which is the term of Notification, its mean the unit card or means the Notification View with the list of card So, this feature is related to the card view component of the View with all the list of cards including the "Notificaciones" Title?
> 
> I'll appreciate your clarification.
> 
> @victorstein

Just the notification component. As shown in the picture.

**Comment by carloslenondavis** [comment]
Which type will be used for **"date"** prop? string or it'll be a date object?.

**Comment by victorstein** [comment]
That is a good question. For now, let's leave it as a date string. @GustavoGomez092 can you confirm the data type coming from the API.

**Comment by carloslenondavis** [comment]
> Id d'nt find any example in the code for the way how the type should be declared for each component prop.

**_So, in order to follow alignments:_**
1. We should use **type** aliases or **interface**?
2. In which place this type/interface should be declared? inside the .tsx file or in whith other file
3. The naming convention for the type or interface

You can see in the above screenshot how currently I have it using type aliases

![image](https://github.com/victorstein/TGC/assets/4239218/fe104690-a480-46a8-ab49-601bc6207498)

**Comment by victorstein** [comment]
1. We should use **type** aliases or **interface**?
```Interfaces are always preferred over types to declare props```
2. In which place this type/interface should be declared? inside the .tsx file or in whith other file
```in its own component-name.types.ts file```
3. The naming convention for the type or interface
```IinterfaceName notice the capital I before the interface name. Which will be the component name ideally. ```

**Comment by carloslenondavis** [comment]
Hi guys,

I seeing that in the app we're using light and dark color scheme.

So, this dark schema will be added to the Notification component?, 

_-if yes-_
Which should be the color pallete for its when the dark color schema activated?.

@victorstein

**Comment by carloslenondavis** [comment]
For common styles, specificaly for colors, font color, font size, etc..
Should we use a common constant file, or each component will be responsible for they own styles, even if those are repeated?
Do we using any theme pallete set or some contstant styles?

**Comment by victorstein** [comment]
> Hi guys,
> 
> I seeing that in the app we're using light and dark color scheme.
> 
> So, this dark schema will be added to the Notification component?

```The notification component has a dark variant which you can see in the figma file.```

> _-if yes-_ Which should be the color pallete for its when the dark color schema activated?.

```check the figma file for reference. The dark variants are below the light variants.```

> @victorstein

**Comment by victorstein** [comment]
> For common styles, specificaly for colors, font color, font size, etc.. Should we use a common constant file, or each component will be responsible for they own styles, even if those are repeated? Do we using any theme pallete set or some contstant styles?

The tailwind theme specifies the colors. Feel free to add any missing color. Regarding how to use the dark variant, notice the ```dark:``` styles in the already built components. For more information on how Tailwind's dark theme works refer to the docs.

**Comment by carloslenondavis** [comment]
I having an issue with the title text,
The content is **overpasing the container**. I tried to fix it setting the `flexWrap: 'wrap'` and the `flexShrink` style prop. But its till not working. 

Do you have any idea how to fix this, maybe I missing something.

![image](https://github.com/victorstein/TGC/assets/4239218/bbb2a3eb-719b-4145-8a34-e2b237d5cac2)

These are the tsx structre of the component 
![image](https://github.com/victorstein/TGC/assets/4239218/f861fccb-02b2-46a3-989c-5d6e2cc08fae)

**Comment by victorstein** [comment]
> I having an issue with the title text, The content is **overpasing the container**. I tried to fix it setting the `flexWrap: 'wrap'` and the `flexShrink` style prop. But its till not working.
> 
> Do you have any idea how to fix this, maybe I missing something.
> 
> ![image](https://private-user-images.githubusercontent.com/4239218/307245839-bbb2a3eb-719b-4145-8a34-e2b237d5cac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzMwNTcsIm5iZiI6MTcwODY3Mjc1NywicGF0aCI6Ii80MjM5MjE4LzMwNzI0NTgzOS1iYmIyYTNlYi03MTliLTQxNDUtOGEzNC1lMmIyMzdkNWNhYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDcxOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYyNzRjMDI4MWY1MmEwNzYwZmZlOTlkOWQ4ZTg3OWE0MThmZDY4ZGM3YWRlY2Q3ZDc4NDcxY2VlZTAyMDcxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q-m6pliA6lHVN8QMhZvbO2ftJCqFMXXyCWbkeO69v8U)
> 
> These are the tsx structre of the component ![image](https://private-user-images.githubusercontent.com/4239218/307246610-f861fccb-02b2-46a3-989c-5d6e2cc08fae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzMwNTcsIm5iZiI6MTcwODY3Mjc1NywicGF0aCI6Ii80MjM5MjE4LzMwNzI0NjYxMC1mODYxZmNjYi0wMmIyLTQ2YTMtOTg5Yy01ZDZlMmNjMDhmYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDcxOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE5NTJkYWQyNTE5MDAzMWUyNWE2MGQ3Zjg4MTljZGZlNWE4YmVlMmE2ZWQ3ZTM3YmJiMTQ4ZjlmYjM5MGY5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XVYwIKsk8jemahcn2Z6U0h7-hxXh7KeFZhdKe4wRDWs)

Please migrate this to tailwind classes. The component seems to be structured well but I don't know what styles you are using once migrated to tailwind classes I will be able to tell the problem a little better.

Please refrain from using the stylesheet api unless absolutely necessary. This will ensure we keep the components consistent.

**Comment by carloslenondavis** [comment]
Thanks for the info,

**Comment by carloslenondavis** [comment]
Hi guys,
I still having an issue with the content overpassing the text container. I already follow the **nativewind** styles using the **`flex-wrap`** prop. I try diff options but its sitll not working.

I do not know if I may missing something. 
I'll appreaciate your help.

![image](https://github.com/victorstein/TGC/assets/4239218/1a4273e9-374c-4168-9030-b5098b0a7af2)

**Comment by victorstein** [comment]
Try making the container flex.

**Comment by victorstein** [comment]
Will check on this tomorrow

**Comment by carloslenondavis** [comment]
> Try making the container flex.

I already did that, and its still overpassing

**Comment by carloslenondavis** [comment]
> Will check on this tomorrow

Perfect.
See you later

**Comment by GustavoGomez092** [comment]
Try using a StyledView instead of a view:

```import { Text, View } from 'react-native';
import { styled } from 'nativewind';

const StyledView = styled(View)
const StyledText = styled(Text)

const Component = () => {
  return (
    <StyledView className="flex">
      <StyledText className="text-slate-800">
        Try editing me
      </StyledText>
    </StyledView>
  );
}```

**Comment by carloslenondavis** [comment]
Thanks for the info @GustavoGomez092, 
In fact I was reading about styledView. 
I'll check with that change
